### ISSUE TITLE
highlight link Scrollbar XX does not working?

### ISSUE THREAD

**Issue by khughitt** [sslivkoff/vim-scroll-barnacle#2]
It's possible that I am simply misunderstanding what are appropriate settings to use here, but I've tried a few different options, e.g.:

highlight link Scrollbar Include
highlight link Scrollbar TabLineSel
highlight link Scrollbar Todo
highlight link Scrollbar Float

None of them seem to affect the scrollbar appearance.

Any suggestions?

**Comment by sslivkoff** [comment]
Ah, there was a typo in the examples. `ScrollbarBar` was the highlight group. There's an extra `Bar` in there because I was thinking that eventually it might be useful to also have `ScrollbarBackground` as a highlight group. But condensing fg and bg into a single highlight group might be a vimmier way to do it if the bar only has fg and the background only has bg.

But `ScrollbarBar` is a clunky name, changed to `Scrollbar` in 7b4dfa0fb22a4047130feb0c3a2bbcdeb5127969
